### ISSUE TITLE
broken price predictions when the sunday price isn't specified

### ISSUE THREAD

**Issue by Dzwiedziasty** [mikebryant/ac-nh-turnip-prices#258]
https://turnipprophet.io?prices=.82.78.74.69.66.62.54.95.142.560..&pattern=3

setting the sunday price to around 100 fixes the graph

**Comment by mikebryant** [comment]
Fixed by #262 :)

@Dzwiedziasty thanks for reporting this. Best of luck with your turnip prices!

**Comment by Dzwiedziasty** [comment]
#262 didn't fix the issue fully - the large spike pattern still isn't predicted correctly if the last price isn't specified
https://turnipprophet.io?prices=.82.78.74.69.66.62.54.95.142...&pattern=3
